# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'developerFiles/probabilistic_map_algebra_tool_dialog_base.ui'
#
# Created: Wed May 06 15:57:13 2015
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BBNToolbox(object):
    def setupUi(self, BBNToolbox):
        BBNToolbox.setObjectName(_fromUtf8("BBNToolbox"))
        BBNToolbox.resize(484, 739)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BBNToolbox.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(BBNToolbox)
        self.buttonBox.setGeometry(QtCore.QRect(120, 490, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.label = QtGui.QLabel(BBNToolbox)
        self.label.setGeometry(QtCore.QRect(20, 80, 269, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(BBNToolbox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 269, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayoutWidget = QtGui.QWidget(BBNToolbox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 441, 27))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_file = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_file.setEnabled(False)
        self.lineEdit_file.setAcceptDrops(True)
        self.lineEdit_file.setReadOnly(True)
        self.lineEdit_file.setObjectName(_fromUtf8("lineEdit_file"))
        self.horizontalLayout.addWidget(self.lineEdit_file)
        self.pushButton_browsefile = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_browsefile.setObjectName(_fromUtf8("pushButton_browsefile"))
        self.horizontalLayout.addWidget(self.pushButton_browsefile)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(BBNToolbox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 441, 25))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_folder = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_folder.setEnabled(False)
        self.lineEdit_folder.setReadOnly(True)
        self.lineEdit_folder.setObjectName(_fromUtf8("lineEdit_folder"))
        self.horizontalLayout_2.addWidget(self.lineEdit_folder)
        self.pushButton_browsefolder = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_browsefolder.setObjectName(_fromUtf8("pushButton_browsefolder"))
        self.horizontalLayout_2.addWidget(self.pushButton_browsefolder)
        self.progressMap = QtGui.QProgressBar(BBNToolbox)
        self.progressMap.setGeometry(QtCore.QRect(20, 600, 441, 23))
        self.progressMap.setProperty("value", 0)
        self.progressMap.setObjectName(_fromUtf8("progressMap"))
        self.progressRun = QtGui.QProgressBar(BBNToolbox)
        self.progressRun.setGeometry(QtCore.QRect(20, 650, 441, 23))
        self.progressRun.setProperty("value", 0)
        self.progressRun.setObjectName(_fromUtf8("progressRun"))
        self.label_7 = QtGui.QLabel(BBNToolbox)
        self.label_7.setGeometry(QtCore.QRect(20, 580, 231, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(BBNToolbox)
        self.label_8.setGeometry(QtCore.QRect(20, 630, 251, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.progressPlot = QtGui.QProgressBar(BBNToolbox)
        self.progressPlot.setGeometry(QtCore.QRect(20, 700, 441, 23))
        self.progressPlot.setProperty("value", 0)
        self.progressPlot.setObjectName(_fromUtf8("progressPlot"))
        self.label_9 = QtGui.QLabel(BBNToolbox)
        self.label_9.setGeometry(QtCore.QRect(20, 680, 231, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(BBNToolbox)
        self.label_10.setGeometry(QtCore.QRect(20, 550, 121, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.groupBox = QtGui.QGroupBox(BBNToolbox)
        self.groupBox.setGeometry(QtCore.QRect(20, 400, 441, 71))
        self.groupBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 401, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_f = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_f.setChecked(True)
        self.radioButton_f.setObjectName(_fromUtf8("radioButton_f"))
        self.horizontalLayout_3.addWidget(self.radioButton_f)
        self.radioButton_s = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioButton_s.setObjectName(_fromUtf8("radioButton_s"))
        self.horizontalLayout_3.addWidget(self.radioButton_s)
        self.checkBox_canvas = QtGui.QCheckBox(BBNToolbox)
        self.checkBox_canvas.setGeometry(QtCore.QRect(30, 500, 131, 17))
        self.checkBox_canvas.setObjectName(_fromUtf8("checkBox_canvas"))
        self.line = QtGui.QFrame(BBNToolbox)
        self.line.setGeometry(QtCore.QRect(20, 530, 441, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.groupBox_2 = QtGui.QGroupBox(BBNToolbox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 180, 441, 91))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 61))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkBox_ev = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_ev.setObjectName(_fromUtf8("checkBox_ev"))
        self.verticalLayout.addWidget(self.checkBox_ev)
        self.checkBox_std = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_std.setObjectName(_fromUtf8("checkBox_std"))
        self.verticalLayout.addWidget(self.checkBox_std)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 20, 201, 61))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkBox_mp = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_mp.setObjectName(_fromUtf8("checkBox_mp"))
        self.verticalLayout_2.addWidget(self.checkBox_mp)
        self.checkBox_pmp = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBox_pmp.setObjectName(_fromUtf8("checkBox_pmp"))
        self.verticalLayout_2.addWidget(self.checkBox_pmp)
        self.groupBox_3 = QtGui.QGroupBox(BBNToolbox)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 280, 441, 111))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.checkBox_ign = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ign.setGeometry(QtCore.QRect(10, 20, 251, 20))
        self.checkBox_ign.setObjectName(_fromUtf8("checkBox_ign"))
        self.checkBox_cp = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_cp.setGeometry(QtCore.QRect(10, 50, 411, 20))
        self.checkBox_cp.setObjectName(_fromUtf8("checkBox_cp"))
        self.checkBox_sim = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_sim.setGeometry(QtCore.QRect(10, 80, 141, 20))
        self.checkBox_sim.setObjectName(_fromUtf8("checkBox_sim"))
        self.doubleSpinBox_ign = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_ign.setGeometry(QtCore.QRect(320, 20, 101, 22))
        self.doubleSpinBox_ign.setMaximum(100.0)
        self.doubleSpinBox_ign.setSingleStep(1.0)
        self.doubleSpinBox_ign.setObjectName(_fromUtf8("doubleSpinBox_ign"))
        self.doubleSpinBox_cp = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.doubleSpinBox_cp.setGeometry(QtCore.QRect(320, 50, 101, 22))
        self.doubleSpinBox_cp.setMaximum(999999999.0)
        self.doubleSpinBox_cp.setObjectName(_fromUtf8("doubleSpinBox_cp"))
        self.checkBox_allowPassword = QtGui.QCheckBox(BBNToolbox)
        self.checkBox_allowPassword.setGeometry(QtCore.QRect(20, 140, 191, 17))
        self.checkBox_allowPassword.setObjectName(_fromUtf8("checkBox_allowPassword"))
        self.lineEdit_password = QtGui.QLineEdit(BBNToolbox)
        self.lineEdit_password.setEnabled(False)
        self.lineEdit_password.setGeometry(QtCore.QRect(220, 140, 241, 20))
        self.lineEdit_password.setObjectName(_fromUtf8("lineEdit_password"))

        self.retranslateUi(BBNToolbox)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), BBNToolbox.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), BBNToolbox.reject)
        QtCore.QMetaObject.connectSlotsByName(BBNToolbox)

    def retranslateUi(self, BBNToolbox):
        BBNToolbox.setWindowTitle(QtGui.QApplication.translate("BBNToolbox", "Probabilistic Map Algebra Tool (PMAT)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BBNToolbox", "Bayesian belief network model (.neta):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BBNToolbox", "Input map (.tif) directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browsefile.setText(QtGui.QApplication.translate("BBNToolbox", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browsefolder.setText(QtGui.QApplication.translate("BBNToolbox", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BBNToolbox", "Combining input maps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("BBNToolbox", "Running Bayesian belief network", None, QtGui.QApplication.UnicodeUTF8))
        self.progressPlot.setFormat(QtGui.QApplication.translate("BBNToolbox", "%p% ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BBNToolbox", "Plotting output maps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("BBNToolbox", "PROGRESS:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BBNToolbox", "Calculation speed", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_f.setText(QtGui.QApplication.translate("BBNToolbox", "Fast", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_s.setText(QtGui.QApplication.translate("BBNToolbox", "Slow", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_canvas.setText(QtGui.QApplication.translate("BBNToolbox", "Add output to canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BBNToolbox", "Standard output maps", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ev.setText(QtGui.QApplication.translate("BBNToolbox", "Expected value", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_std.setText(QtGui.QApplication.translate("BBNToolbox", "Standard deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_mp.setText(QtGui.QApplication.translate("BBNToolbox", "Most probable state", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pmp.setText(QtGui.QApplication.translate("BBNToolbox", "Probability of most probable state", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("BBNToolbox", "Advanced output maps", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ign.setText(QtGui.QApplication.translate("BBNToolbox", "Ignorance map with threshold probability (%): ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_cp.setText(QtGui.QApplication.translate("BBNToolbox", "Cumulative probability map (P(output>x)) with threshold: ", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sim.setText(QtGui.QApplication.translate("BBNToolbox", "Sampled map", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_allowPassword.setText(QtGui.QApplication.translate("BBNToolbox", "Insert Netica API license (optional):", None, QtGui.QApplication.UnicodeUTF8))

